<a href="https://colab.research.google.com/github/beom0124/Hongong-ML-DL/blob/main/Logistic_Regresion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LogisticRegression
from scipy.special import expit
from scipy.special import softmax

fish = pd.read_csv('https://bit.ly/fish_csv')
fish.head()

print(pd.unique(fish['Species']))
fish_input = fish[['Weight','Length','Diagonal','Height','Width']].to_numpy()
fish_target = fish['Species'].to_numpy()

train_input, teat_input, train_target, test_target =train_test_split(fish_input, fish_target,random_state = 42)

ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(teat_input)

kn = KNeighborsClassifier()
kn.fit(train_scaled, train_target)

proba = kn.predict_proba(test_scaled[:5])
print(np.round(proba, decimals=4))

distances, indexes = kn.kneighbors(test_scaled[3:4])
print(train_target[indexes])

bream_smelt_indexes = (train_target == 'Bream') | (train_target == 'Smelt')
train_bream_smelt = train_scaled[bream_smelt_indexes]
target_bream_smelt = train_target[bream_smelt_indexes]

# lr = LogisticRegression() 로직스틱 회귀를 통한 이진분류
# lr.fit(train_bream_smelt, target_bream_smelt)

# print(lr.predict(train_bream_smelt[:5]))

# print(lr.predict_proba(train_bream_smelt[:5]))

# decision = lr.decision_function(train_bream_smelt[:5])
# print(decision) #Logistic Regression이 학습한 계수
# print(expit(decision))


lr = LogisticRegression(C=20, max_iter=1000) # C는 규제를 제어하는 매개변수(작을수록 크게 규제), iter는 반복 횟수
lr.fit(train_scaled, train_target)
print(lr.score(train_scaled, train_target))
print(lr.score(test_scaled, test_target))

# proba = lr.predict_proba(test_scaled[:5])
# print(np.round(proba, decimals = 3))

decision = lr.decision_function(test_scaled[:5])
print(np.round(decision, decimals=3))

proba = softmax(decision, axis =1)
print(np.round(proba, decimals = 3))

['Bream' 'Roach' 'Whitefish' 'Parkki' 'Perch' 'Pike' 'Smelt']
[[0.  0.  0.6 0.  0.4 0.  0. ]
 [0.  0.  0.  0.  0.  1.  0. ]
 [0.  0.  0.2 0.8 0.  0.  0. ]
 [0.  0.  0.8 0.  0.2 0.  0. ]
 [0.  0.  0.8 0.  0.2 0.  0. ]]
[['Roach' 'Perch' 'Perch' 'Perch' 'Perch']]
0.9327731092436975
0.925
[[ -6.498   1.032   5.164  -2.729   3.339   0.327  -0.634]
 [-10.859   1.927   4.771  -2.398   2.978   7.841  -4.26 ]
 [ -4.335  -6.233   3.174   6.487   2.358   2.421  -3.872]
 [ -0.683   0.453   2.647  -1.187   3.265  -5.753   1.259]
 [ -6.397  -1.993   5.816  -0.11    3.503  -0.112  -0.707]]
[[0.    0.014 0.841 0.    0.136 0.007 0.003]
 [0.    0.003 0.044 0.    0.007 0.946 0.   ]
 [0.    0.    0.034 0.935 0.015 0.016 0.   ]
 [0.011 0.034 0.306 0.007 0.567 0.    0.076]
 [0.    0.    0.904 0.002 0.089 0.002 0.001]]
